# Generated by Django 4.2 on 2023-04-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='activitylog',
            old_name='peoples',
            new_name='persons',
        ),
    ]
